package com.space.subadmin.payment

import java.math.BigDecimal

// --- Data Classes Representing Payloads and Tokens ---

/**
 * Raw data read from the customer's card chip.
 */
data class CardData(val pan: String, val cardholderName: String, val expirationDate: String)

/**
 * A one-time-use dynamic cryptogram generated by the card and terminal.
 */
data class DynamicCryptogram(val value: String)

/**
 * The fully encrypted P2PE blob created by the card reader.
 */
data class EncryptedPayload(val encryptedData: String)

/**
 * A non-sensitive token representing the customer's card for future use.
 */
data class PaymentToken(val value: String)

/**
 * Decrypted, parsed transaction details ready for processing.
 */
data class TransactionDetails(
    val merchantId: String,
    val amount: BigDecimal,
    val cardData: CardData,
    val cryptogram: DynamicCryptogram
)

/**
 * The response from the Issuing Bank, containing an official response code.
 */
data class BankAuthorizationResponse(val responseCode: String, val isApproved: Boolean)

/**
 * The final, simplified response sent back to the POS terminal.
 */
data class PosConfirmation(val status: String) // e.g., "Approved" or "Declined"

// --- Interfaces for External Systems and Services ---

interface CardReader {
    fun generateEncryptedPayload(cardData: CardData, amount: BigDecimal, merchantId: String): EncryptedPayload
}

interface PaymentGateway {
    fun processTransaction(payload: EncryptedPayload): PaymentToken
}

interface CardNetwork {
    fun routeToIssuer(details: TransactionDetails): BankAuthorizationResponse
}

interface IssuingBank {
    fun authorize(details: TransactionDetails): BankAuthorizationResponse
}

// --- Main Executioner Class for the Handshake ---

/**
 * Orchestrates the entire POS authorization handshake from start to finish.
 */
class CreateHandshakePayment(
    private val cardReader: CardReader,
    private val paymentGateway: PaymentGateway,
    private val cardNetwork: CardNetwork,
    private val issuingBank: IssuingBank
) {

    /**
     * Executes the full payment authorization flow.
     *
     * @param cardData The data read from the customer's card.
     * @param amount The transaction amount.
     * @param merchantId The ID of the merchant initiating the transaction.
     * @return A final confirmation for the POS terminal.
     */
    fun execute(cardData: CardData, amount: BigDecimal, merchantId: String): PosConfirmation {
        // Step 4 & 5: Capture data, generate cryptogram, and create an encrypted payload.
        val encryptedPayload = cardReader.generateEncryptedPayload(cardData, amount, merchantId)

        // Step 6: The gateway decrypts, parses, and tokenizes the card.
        val token = paymentGateway.processTransaction(encryptedPayload)

        // Simulate the decrypted details for the next steps.
        val transactionDetails = TransactionDetails(
            merchantId = merchantId,
            amount = amount,
            cardData = cardData,
            cryptogram = DynamicCryptogram("cryptogram_value_from_payload") // Placeholder
        )

        // Step 7: The gateway routes the transaction to the correct card network.
        val bankResponse = cardNetwork.routeToIssuer(transactionDetails)

        // Step 8: The issuing bank validates the cryptogram and makes a decision.
        // In a real system, the card network would call the bank. Here we simulate the flow.
        val finalDecision = issuingBank.authorize(transactionDetails)

        // The return journey: The response is sent back to the POS.
        return if (finalDecision.isApproved) {
            PosConfirmation("Approved")
        } else {
            PosConfirmation("Declined")
        }
    }
}
