ktor:
  application:
    modules:
      - com.ideaspace.ApiGatewayApplicationKt.module
  deployment:
    port: 8080

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER:space-master}
  audience: ${JWT_AUDIENCE:space-master-users}
  realm: "Space Master Server"

postgres:
  url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/space_main}
  user: postgres
  password: postgres
  driver: "org.postgresql.Driver"

kafka:
  schema:
    registry:
      url:
        - ${KAFKA_SCHEMA_REGISTRY_URL:http://localhost:8081}
  common:
    bootstrap_servers:
      - ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    client_id: "api-gateway-client"
  document_event_topic: "ideaspace.document.event"


redis:
  host: localhost
  port: 6379

services:
  sync_server_url: "http://localhost:9099"

flavor: ${FLAVOR}