ktor:
  application:
    modules:
      - com.ideaspace.ApplicationKt.module
  deployment:
    port: 8080

#postgres:
#  url: "jdbc:postgresql://localhost:5439/whiteboard"
#  user: postgres
#  password: postgres

kafka:
  schema:
    registry:
      url:
        - ${KAFKA_SCHEMA_REGISTRY_URL:http://localhost:8081}
  common:
    bootstrap_servers:
      - ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    client_id: "api-gateway-client"
  document_event_topic: "ideaspace.document.event"

services:
  sync_server_url: "http://localhost:9099"