developmentMode: true
ktor:
  application:
    modules:
      - com.ideaspace.ApplicationKt.module
  deployment:
    port: 9099
postgres:
  url: "jdbc:postgresql://localhost:5439/idea_space_main"
  user: postgres
  password: postgres

kafka:
  # Use environment variables with sensible defaults for local development.
  # Ktor will use the value of KAFKA_BOOTSTRAP_SERVERS if it's set,
  # otherwise it will fall back to "localhost:9092".
  bootstrap_servers:
    - ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  schema_registry_url: ${KAFKA_SCHEMA_REGISTRY_URL:http://localhost:8081}
  client_id: "sync-server"
  topic: "server-operation"
  consumer_group_id: "sync-server-group"
  document_event_topic: "ideaspace.document.event"
  topic_defaults:
    partitions: ${KAFKA_TOPIC_PARTITIONS:3}
    replicas: ${KAFKA_TOPIC_REPLICAS:1}

redis:
  host: localhost
  port: 6379