# ===================================================================
# PRODUCTION DATABASE CONNECTION SETTINGS
# ===================================================================
# These settings will be used when the 'prod' profile is active.

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

# ===================================================================
# SERVER PORT
# ===================================================================
server.port=8080
gg.jte.developmentMode=false
gg.jte.usePrecompiledTemplates=true